# Auto builds Sphinx docs after each commit

name: Build Sphinx


on:
  push:
    branches: 
      - gh-actions


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with: 
        python-version: 3.7
  
    - name: install packages
      run: |
        pip install -r requirements.txt
        pip install sphinx
        pip install sphinx-rtd-theme
        pip install sphinx-rtd-dark-mode
     
    - name: generate template
      run: sphinx-apidoc -o docs pincer 

    - name: setup git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@pincer.dev"
